main: com.perceivedev.factionswar.FactionsWar
name: FactionsWar
version: 1.0.0
description: A war plugin for FactionsOne
author: [Rayzr]
depend: [PerceiveCore]
commands:
  faction:
    description: Main command for FactionsWar
    # A catch so that if something goes wrong while loading the plugin
    # you'll actually have a nice message instead of showing something
    # like "/faction" (usage)
    #
    # Also kinda nice if you forget to register your command handler :P
    usage: "\u00a7cOops! Something went wrong!"
